[app]
players_whitelist = ['deezer', 'spotify', 'MellowPlayer3', 'GnomeMusic']

[shortcuts]
previous_keys = ['<269025046>']
next_keys = ['<269025047>']
play_pause_keys = ['<269025044>']

[window]
pos_x = 120
pos_y = 70
opacity = 0.8
layout = 'full'

